name: Integration Test
on:
  push:
    branches:
      - main
jobs:
  ami-integration-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Node.js project
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Configure AWS CLI Profile
        run: |
          aws configure --profile github_demo set aws_access_key_id ${{ secrets.DEMO_ACCESS_KEY_ID }}
          aws configure --profile github_demo set aws_secret_access_key ${{ secrets.DEMO_SECRET_ACCESS_KEY }}
          aws configure --profile github_demo set region us-east-1  # Replace with your desired AWS region
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_PROFILE: github_demo

      - name: Wait for MySQL to be ready
        run: |
          until nc -z -v -w30 localhost 3306
          do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done
      - name: Install project dependencies
        run: npm install
      - name: Set up .env
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
      - name: Run Integration tests 
        run: npm test
      - name: Build the Project Artifacts
        run: npm run build
      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.8.3/packer_1.8.3_linux_amd64.zip
          unzip packer_1.8.3_linux_amd64.zip
          sudo mv packer /usr/local/bin/
      
      - name : Packer Integration
        run: packer init .
      - name: Create AMI 
        run: packer build .
      - name: Get the latest Debian AMI ID and Name
        id: get-ami-id-and-name
        run: |
          latest_ami=$(aws ec2 describe-images \
            --owners demo \
            --filters "Name=architecture,Values=x86_64" "Name=state,Values=available" "Name=tag:Name,Values=csye6225_*" \
            --query "Images | sort_by(@, &CreationDate) | [-1].{ID:ImageId,Name:Tags[?Key=='Name'].Value | [0]}" --output json)
          latest_ami_id=$(echo $latest_ami | grep -oP '"ImageId": "\K[^"]+')
          latest_ami_name=$(echo $latest_ami | grep -oP '"Value": "csye6225_\K[^"]+')

          echo "::set-output name=latest_ami_id::$latest_ami_id"
          echo "::set-output name=latest_ami_name::$latest_ami_name"

    
      - name: Create Launch Template
        run: |
          aws ec2 create-launch-template \
            --launch-template-name new_asg_launch_config \
            --version-description "Initial version" \
            --version-number 2 \
            --block-device-mappings "[{\"DeviceName\":\"/dev/sda1\",\"Ebs\":{\"VolumeSize\":your-volume-size}}]" \
            --image-id ${{ needs.get-ami-id-and-name.outputs.latest_ami_id }}

      - name: Update Autoscaling Group
        run: |
          aws autoscaling update-auto-scaling-group \
            --auto-scaling-group-name Ec2-Auto-Scaling-Group \
            --launch-template "LaunchTemplateName=new_asg_launch_config,Version=2"
      