name: Packer Checks
on:
  pull_request:
    branches:
      - main
jobs:
  packer-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.8.3/packer_1.8.3_linux_amd64.zip
          unzip packer_1.8.3_linux_amd64.zip
          sudo mv packer /usr/local/bin/
        if: runner.os == 'Linux'
      - name: Install Packer (macOS)
        run: |
          brew install packer
        if: runner.os == 'macOS'
      - name: Format Packer Templates
        run: packer fmt -check
      - name: Validate Packer Templates
        run: packer validate
